version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: votes
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    networks:
      - backend

  vote:
    build:
      context: ./vote
    container_name: vote
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - redis

  worker:
    build:
      context: ./worker
    container_name: worker
    networks:
      - backend
    depends_on:
      - redis
      - postgres

  result:
    build:
      context: ./result
    container_name: result
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  backend:
